### ISSUE TITLE
A special case that causes issues

### ISSUE THREAD

**Issue by lostsky3000** [erincatto/solver2d#19]
Hi, I have discovered a special case that causes issues in the simulation. 
When the gravity is {0,0}, two identical mass circles that are not rotating are moving toward each other with equal speeds in opposite directions. When the separation between the two circles is 0, the calculated impulse will result in both of them having a linear velocity of 0, causing them to stop moving afterwards. However, they should actually collide and exchange velocities, bouncing back.

Thanks!

**Comment by erincatto** [comment]
That is an inelastic collision and is the correct behavior.

https://en.wikipedia.org/wiki/Inelastic_collision

**Comment by lostsky3000** [comment]
> That is an inelastic collision and is the correct behavior.
> 
> https://en.wikipedia.org/wiki/Inelastic_collision

Yes, I had previously overlooked the fact that this algorithm does not conserve momentum. Thank you.
